### ISSUE TITLE
KenLM support?

### ISSUE THREAD

**Issue by amittai** [rousseau-lium/XenC#1]
Hullo -- is it possible to have KenLM support added? It can produce sentence-level perplexity scores (previous versions did not), and is much more efficient.

**Comment by antho-rousseau** [comment]
Hi, 
indeed KenLM support was planned, it will eventually get added at some point when I have spare time for XenC but honestly I can't tell when exactly this will happen.

Thanks for the reminder anyway.

**Comment by antho-rousseau** [comment]
Hi amittai,

kenlm support has been added to XenC!

Best,
Anthony

**Comment by amittai** [comment]
Super cool! Thanks for telling me -- I'll spread the word :)

~amittai

PS To fill in the space on your to-do list, here's an extra 
preprocessing step that helps perhaps +1.5 BLEU. Results not guaranteed, 
of course ;)
http://workshop2015.iwslt.org/downloads/IWSLT_2015_RP_17.pdf

I'll actually have an implementation up on Github within a week, but 
note that my code isn't as good as yours, so you may want to rewrite it 
entirely.

**Comment by antho-rousseau** [comment]
Great! Will read your paper and add this to XenC when I get some spare time! Thanks!
